
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Prisma client generation does not connect to the database. Keeping a
    // syntactically valid fallback lets tests and container builds run before
    // deployment secrets are present; migrate/start still use DATABASE_URL.
    url: process.env.DATABASE_URL
      ?? "postgresql://portfolio:portfolio-local-only@localhost:5432/portfolio",
  },
});
